### PR TITLE
Feature: IMAGE_TO_RAM option

### PR DESCRIPTION
**Pull request by kvaps**
fixes: https://github.com/ltsp/ltsp/issues/74

### CODE REVIEW

**Comment by alkisg** [comment]
Thank you kvaps,

img_src isn't just a file name but it can be a complicated mount command. Run `man ltsp ipxe` and read the explanation for that line there:

> ltsp.image=ltsp/ubuntu.iso,fstype=iso9660,loop,ro,,casper/filesystem.squashfs,squashfs,loop,ro

So I think you should scan until the first comma, extract the file name (ltsp/ubuntu.iso, relative to /root in this case), copy it to /run/initramfs/ltsp/, and then prefix the new path to img_src so that it becomes:

> /run/initramfs/ltsp/ubuntu.iso,fstype=iso9660,loop,ro,,casper/filesystem.squashfs,squashfs,loop,ro

That way then the rest of the function can continue and execute the rest of the img_src commands, i.e. in this case to mount filesystem.squashfs.

**Comment by kvaps** [comment]
code and documentation is updated, please review

**Comment by alkisg** [comment]
Thank you kvaps,

a couple of small typos, "That's", "byt" and "the". Let's use this instead:

```
: Specifying this option under the [clients] section copies the rootfs
image to RAM during boot. That makes clients less dependent on
the server, but they must have sufficient memory to fit the image. 
```

Here again please test it so that I can commit it directly. :)

**Comment by kvaps** [comment]
Documentation updated, this change is already tested.

**Pull request merged**
