### PR TITLE
Feature: ADD_IMAGE_EXCLUDES OMIT_IMAGE_EXCLUDES options

### PR DESCRIPTION
**Pull request by kvaps**
According https://github.com/ltsp/ltsp/issues/81#issuecomment-555912109

This PR adds two new options, example:

```
ADD_IMAGE_EXCLUDES="foo bar/* baz/sub"
OMIT_IMAGE_EXCLUDES="home/*"
```

Option `ADD_IMAGE_EXCLUDES` will add `foo`, `bar/*` and `baz/sub` to `image.excludes` during mksquashfs call (names containing spaces are not supported, do we really need them?)

Option `OMIT_IMAGE_EXCLUDES` will remove `home/*` from default `image.excludes` during mksquashfs call

### CODE REVIEW

**Comment by kvaps** [comment]
I also like to replace:
```bash
    if [ -f /etc/ltsp/image-local.excludes ]; then
        cat /etc/ltsp/image-local.excludes >> "$ef_merged"
    fi
    if [ -f /etc/ltsp/image.excludes ]; then
        cat /etc/ltsp/image.excludes >> "$ef_merged"
    elif [ -f "$_APPLET_DIR/image.excludes" ]; then
        cat "$_APPLET_DIR/image.excludes" >> "$ef_merged"
    fi
```
to something like
```bash
    for i in \
        /etc/ltsp/image-local.excludes \
        /etc/ltsp/image.excludes \
        "$_APPLET_DIR/image.excludes"
    do
        if [ -f "$i" ]; then
            cat "$i" >> "$ef_merged"
        fi
    done
```

do you like this change?:w

**Comment by kvaps** [comment]
> > To include home/* one way would be to clone image.excludes to /etc/ltsp while omitting that line.
> This will not work, because both files are used, local and upstream one:
> https://github.com/ltsp/ltsp/blob/master/ltsp/server/image/65-mksquashfs.sh#L30-L31

> >    This will not work, because both files are used
>
>No. There are two local files: image.excludes overrides the upstream one, while image-local.excludes is an additional one.

I'm sure, in my case they were appended, not replaced:

```
# grep home /usr/share/ltsp/server/image/image.excludes /etc/ltsp/image-local.excludes
/usr/share/ltsp/server/image/image.excludes:home/*
/etc/ltsp/image-local.excludes:#home/*
# mksquashfs /srv/ltsp/x86_64/ /srv/ltsp/images/x86_64.img -noappend -wildcards -ef /usr/share/ltsp/server/image/image.excludes -ef /etc/ltsp/image-local.excludes
...
# mount /srv/ltsp/images/x86_64.img /mnt
# ls /mnt/home/
<nothing>
# ls /srv/ltsp/x86_64/home/
kvaps
```

**Comment by alkisg** [comment]
The file /srv/ltsp/image.excludes overrides /usr/share/ltsp/server/image/image.excludes.

What are the contents of your /srv/ltsp/image.excludes ?

**Comment by kvaps** [comment]
The same one, I've just commented home/* direcory

```diff
--- /usr/share/ltsp/server/image/image.excludes
+++ /etc/ltsp/image-local.excludes
@@ -12,7 +12,7 @@
 etc/NetworkManager/system-connections/*
 etc/ssh/ssh_host_*
 etc/udev/rules.d/??-persistent-*.rules
-home/*
+#home/*
 lost+found/*
 media/*
 mnt/*
```

**Comment by alkisg** [comment]
I don't think this file supports comments.
The initial comments on top can actually match filenames, and I was hoping that noone would name their files "SPDX-License-Identifier: GPL-3.0-or-later".
Try removing the home/* line completely.

Also, while mksquashfs is running, do a `ps aux | grep mksquashfs`, and paste the command line here; it should show that /usr/share/ltsp/server/image/image.excludes is **not** passed to mksquashfs.

**Comment by kvaps** [comment]
mksquashfs supports comment, this is evidence, look:

default command (with two `-ef`) excludes home:
```
mksquashfs /srv/ltsp/x86_64/ /srv/ltsp/images/x86_64.img -noappend -wildcards -ef /usr/share/ltsp/server/image/image.excludes -ef /etc/ltsp/image-local.excludes
```
command with only modified file (single `-ef`):
```
mksquashfs /srv/ltsp/x86_64/ /srv/ltsp/images/x86_64.img -noappend -wildcards -ef /etc/ltsp/image-local.excludes
```

**Comment by alkisg** [comment]
I mean this:

```shell
$ touch /etc/ltsp/image.excludes
$ ltsp image /
```

Then in another shell:

```shell
$ ps aux | grep mksquashfs
mksquashfs /tmp/tmp.efym5nPQol/root /srv/ltsp/images/bionic-nfs.img.tmp -noappend -wildcards -ef /etc/ltsp/image.excludes
```

See, it doesn't use /usr/share/ltsp/server/image/image.exclude at all. It only uses /etc/ltsp/image.excludes.

**Comment by kvaps** [comment]
Thats's weird, because I have:
```
mksquashfs /tmp/tmp.yCALcg37y1/root /srv/ltsp/images/x86_64.img.tmp -noappend -wildcards -ef /usr/share/ltsp/server/image/image.excludes -ef /etc/ltsp/image-local.excludes
```

**Comment by kvaps** [comment]
Got it, there were some confusion about using different configs in `/etc/ltsp`
You were using: `/etc/ltsp/image.excludes`
I was using: `/etc/ltsp/image-local.excludes`

**Comment by kvaps** [comment]
PR rebased to satisfy existing logic

**Comment by alkisg** [comment]
Thank you kvaps, I only have time for a glance now; I will properly review some other day;

>  ef_merged="$BASE_DIR/images/$_IMG_NAME.excludes" 

Better use the temp dir there instead of the images directory.

> for pattern in $OMIT_IMAGE_EXCLUDES; do 

Globs need to be disabled in shell for this to work properly, i.e. `set -f`.

Also, I expect 95% of the users not to use [ADD|OMIT]_IMAGE_EXCLUDES, so it might be best, if they're not defined, to use the upstream image.excludes directly, without generating an identical temporary one.

**Comment by kvaps** [comment]
Code updated according recommendations

**Comment by alkisg** [comment]
I think we should be able to [use comm](https://stackoverflow.com/questions/4366533/how-to-remove-the-lines-which-appear-on-file-b-from-another-file-a) for this. OMIT_IMAGE_EXCLUDES would go to its stdin, and the upstream image.excludes would be the second parameter. We'd gather that result, and then add ADD_IMAGE_EXCLUDES. The final text would be written to the temporary file passed to mksquashfs.

**Comment by alkisg** [comment]
Give me time I'll try to implement this one within a week.

**Comment by alkisg** [comment]
Here's my final idea, in case you have time to implement this sooner than me.
{OMIT,ADD}_IMAGE_EXCLUDES would be either files or single/multiline entries (one entry per line), similar to [GDM3_CONF](https://github.com/ltsp/ltsp/blob/master/ltsp/client/init/55-display-manager.sh#L56).
Example:

```shell
OMIT_IMAGE_EXCLUDES="home/*"
ADD_IMAGE_EXCLUDES="/etc/ltsp/image-local.excludes"
```

So we don't hardcode any filenames except for the upstream one, and we call `comm` for the line merging without using for loops or `set -f`.

**Comment by kvaps** [comment]
Well, the last word is yours, but I still thinking that using multiline variables was better solution for that.
Me (as a user) would prefer to having these functions identical usage.

Nevertheless `ADD_IMAGE_EXCLUDES` is not so common function so it might be provided as it is right now (just checking `/etc/ltsp/image-local.excludes` file and if so then use it during each run)
Other words I don't see any benefits for using `ADD_IMAGE_EXCLUDES` in this design.

What if we will implement the only `OMIT_IMAGE_EXCLUDES` function instead?

**Comment by alkisg** [comment]
I think you misunderstood me. They are either single line, or multiline, or files. More examples:

```shell
# Someone that wants to exclude 2 additional folders:
ADD_IMAGE_EXCLUDES="
/var/swap/*
/var/swap/.*
"

# Someone that doesn't want to exclude home:
OMIT_IMAGE_EXCLUDES="
/home/*
/srv/*
"
```

The only limitation is that we want one entry per line (instead of space-separated) so that comm can be used.

**Comment by kvaps** [comment]
OK, you just [wrote](https://github.com/ltsp/ltsp/issues/81#issuecomment-555912109)

    I'm not sure if we'll want to suggest multiline values by default, or if multiple variables would be better, e.g. ADD_IMAGE_EXCLUDES_FOO="foo", ADD_IMAGE_EXCLUDES_BAR="bar" etc.

So I've decided that you get rid from this realization.

OK, so let's make them multiline with `comm` comparsion

**Comment by alkisg** [comment]
Yeah the [final idea there](https://github.com/ltsp/ltsp/pull/83#issuecomment-558055756) was meant to override the initial "I'm not sure if..." thought.

My hesitation was if other packages would need to add their own ADD/OMIT variables, e.g. the epoptes package might want to exclude /etc/epoptes/*.crt. But they can just append to the single multiline variables that we'll be using.

**Comment by kvaps** [comment]
@alkisg something like [that](https://github.com/ltsp/ltsp/pull/83/files)?

**Comment by alkisg** [comment]
Thank you kvaps, fix committed in e780fbb61c42400c9dc659a95014925bae0b1a78.

I didn't test it too much, please test if you want.

**Pull request closed without merging**
