### PR TITLE
Feature: OMIT_FUNCTIONS option

### PR DESCRIPTION
**Pull request by kvaps**
According https://github.com/ltsp/ltsp/issues/81#issuecomment-555820881

### CODE REVIEW

**Comment by alkisg** [comment]
Thank you kvaps,
some minor details:

-  Could you put it before `run_parameters` so that it's alphabetically sorted? Both the function and the call.
- Please declare fun [like this](https://github.com/ltsp/ltsp/blob/master/ltsp/ltsp#L183), as `function` is a reserved word in bash.
- Finally it would be great if you could add a tiny documentation about it in the ltsp.conf man page.

**Comment by kvaps** [comment]
resolved, please review

**Comment by alkisg** [comment]
Thank you kvaps,

Just a small typo, "fuction". Let's use this instead:

```
: A space separated list of function names that should be omitted.
The functions specified here will not be executed when called.
This option can be specified in any [section].
```

P.S. it looks fine to me but I haven't tested it; please make sure that it runs so that I commit it directly without testing. ;)

**Comment by kvaps** [comment]
Documentation updated, this change is already tested.

**Pull request merged**
