### PR TITLE
Show applets in ltsp --help

### PR DESCRIPTION
**Pull request by kvaps**
According discussion in #79

```bash
# ltsp --help
Usage: ltsp [-b base-dir] [-h] [-m home-dir] [-o overwrite] [-t tftp-dir] [-V] [applet] [applet-options]

The following applets are currently defined:
·   dnsmasq: configure dnsmasq for LTSP
·   image: generate a squashfs image from an image source
·   info: gather support information about the LTSP installation
·   initrd: create the ltsp.img initrd add-on
·   ipxe: install iPXE binaries and configuration in TFTP
·   kernel: copy the kernel and initrd from an image to TFTP
·   nfs: configure NFS exports for LTSP

Run the specified LTSP applet with applet-options. To get help with applets and their options, run `man ltsp applet` or `ltsp --help applet`.

For extensive help, run: man ltsp
```

### CODE REVIEW

**Comment by alkisg** [comment]
Thank you kvaps,

the `head -n -1` part doesn't work properly if the terminal is e.g. 80 chars wide. I would completely omit `head`, and I would put the APPLETS section after the DESCRIPTION section.

I'm also tempted to additionally `sed 's/^\([^ ]\)   /  \1 /'` to have the bullet list show up better... what do you think?

**Comment by alkisg** [comment]
About the man dependency, you're right, we should put it to Recommends. Not Depends, it's too much, as some people might want to completely avoid man and use online help in order to minimize the space.

**Comment by kvaps** [comment]
done, let me know if you like condensed format (without empty lines)

**Comment by alkisg** [comment]
Thank you kvaps, yeah I think I prefer this condensed one, please change it so that I push your merged PR:

```shell
    printf "Usage: %s\n\n%s\n\n%s\n\nFor extensive help, run: %s\n" \
        "$(echo "$text" | sed -n '/^SYNOPSIS/,/^[^ ]/s/^\(       \|$\)//p')" \
        "$(echo "$text" | sed -n '/^DESCRIPTION/,/^[^ ]/s/^\(       \|$\)//p')" \
        "$(echo "$text" | sed -n '/^APPLETS/,/^[^ ]/s/^\(       \)//p' | sed 's/^\([^ ]\)   /  \1 /')" \
        "$cmd"
```

**Comment by alkisg** [comment]
Ty, merged. :)

**Pull request merged**
